### PR TITLE
Fix media queries

### LINKED ISSUE #5: Media queries should be "bottom-up"
The original http://flexboxgrid.com/ implementation uses media queries such as:

```css
/* for 'sm' class */
@media only screen and (min-width: 48em)
``` 

but using this package, I noticed that it generates media queries that translate to:

```css
/* for 'sm' class */
@media only screen and (min-width: 48em) and (max-width: 64em) 
``` 

This makes it harder to design simple queries because you need to write

```jsx
<Col xs={12} sm={7} md={7} lg={7} />
```

instead of 

```jsx
<Col xs={12} sm={7} />
```

### PR DESCRIPTION
**Pull request by Soreine**
This fix #5 
It just removes the upper limit on media queries, to simplify the use of the library

I haven't seen somewhere in the tests where we can check the generated styles, so... I just updated the snapshots and called it done.

### CODE REVIEW

**Comment by Soreine** [comment]
Side question: @patrickml are you still using/maintaining this project ?

**Comment by patrickml** [comment]
@soreine with my current job I’m unable to without repercussion. Would you be willing to take it over?

**Comment by patrickml** [comment]
And sorry it took so long to reply I never record any notification. Let me know though if you are interested in taking over and I’ll make you a contributor on here and npm

**Comment by Soreine** [comment]
Sure, I'm open to maintain it. Maybe in a year or two we will have to find
someone else. Do I need your approval for every action on this repository ?
I'll be maintaining it with the same quality we maintain our libraries at
GitBook. As long as we are using it, you can be sure it will be in good
hands and follow proper NPM versioning.

I was wondering if this library is used in production currently for an
existing product (no need to mention the name) ?

Le 1 févr. 2018 12:05 AM, "Patrick Lewis" <notifications@github.com> a
écrit :

**Comment by patrickml** [comment]
I give you full permission to change what ever you think will be best for the package.

**Comment by patrickml** [comment]
When ever you see fit.

**Comment by Soreine** [comment]
This PR is a breaking change. I'll release it under 2.0.0
I would like to release the other PR as 1.0.5
To do so, I need NPM permission to publish the package. Here is my profile https://www.npmjs.com/~soreine

**Comment by patrickml** [comment]
done

**Pull request merged**
